"""empty message

Revision ID: 3fb37c14ee4c
Revises: dd7c035d8f93
Create Date: 2020-07-31 01:40:43.711684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb37c14ee4c'
down_revision = 'dd7c035d8f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('ticket', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'ticket')
    # ### end Alembic commands ###
