"""empty message

Revision ID: fa1495678db3
Revises: 6c356bfa517d
Create Date: 2020-07-30 23:24:42.650320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1495678db3'
down_revision = '6c356bfa517d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('about', sa.String(length=140), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_id'), 'driver', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_id'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
